### ISSUE TITLE
Centralize initialization information

### ISSUE THREAD

**Issue by mcgibbon** [CliMT/climt#10]
Some objects like RRTMG have information about default initial values. This should probably be moved to the central location where this information is stored in CliMT, so that it is in one easier-to-find place. At least, it doesn't make sense to specify *some* default values/initialization functions for quantities but not others. Another solution would be to specify initialization values/functions for all quantities within all objects.

**Comment by JoyMonteiro** [comment]
I just checked, but all of them seem to have default values. Do you mean some are `None` and others are not? All the `None` initial values correspond to constants acquired by `replace_none_by_default`. In some other modules, some physical constants have not yet been transferred to sympl, so they appear in the object, but these should be moved eventually.

If we are considering eliminating `replace_none_by_default` entirely, then this issue should go away by itself.

**Comment by mcgibbon** [comment]
I'm talking about values used by get_default_state.

**Comment by JoyMonteiro** [comment]
These values are there to override default initialization information available in `initialization.py`. This was necessary to do since components might require custom array shapes, whereas those in `initialization.py` correspond to some generic shape.

However, I understand what you are saying, and that has been on the cards -- `ClimtPrognostic` (and others) will define an `__init__` method which will create `_input_properties` (and others) using `_climt_inputs`, which will contain all initialization information. This will require each subclass to call `super().__init__`, which will then make the component fully `sympl` compatible.

I plan to get to this sometime this month.

**Comment by mcgibbon** [comment]
We should discuss this when we Skype on Monday, I have some other ideas on how this could be done with simpler programming features.

**Comment by JoyMonteiro** [comment]
sounds good!

**Comment by JoyMonteiro** [comment]
I think this has been handled in recent commits. Some further issues may crop up during the upgrade to 0.4, but they are not directly related to this.

Closed by https://github.com/CliMT/climt/pull/28
