### ISSUE TITLE
pip install forces numpy version 0.16

### ISSUE THREAD

**Issue by quillan86** [CliMT/climt#124]
* CliMT version:  v.0.16.9
* Python version: 3.7
* Operating System: Windows

### Description

When I install climt, it forces install of numpy 0.16.0 even if I have an already later version installed - this breaks when I install in an anaconda environment. 

### What I Did

```
pip install climt
```
I know the issue's located here:

https://github.com/CliMT/climt/blob/develop/setup.py

```
requirements = [
    'numpy==1.16.0',
    'pint>=0.7.0',
    'xarray>=0.8.0',
    'sympl==0.4.0',
    'cython>=0.25',
    'scipy>=0.18.1',
]
```

**Comment by JoyMonteiro** [comment]
Hello,

We were forced to freeze the numpy version since the dynamical core tests simply
failed with some versions of numpy.

This should be written down in the docs somewhere, but for this reason we recommend
using climt within a virtual environment of its own, so that it does not break any existing
installations.

**Comment by mcgibbon** [comment]
Could we pin the version in `requirements_dev.txt` and use that as the environment for testing, but unpin the version (setting a minimum) in setup.py to allow users to attempt to use it with newer versions?

**Comment by JoyMonteiro** [comment]
We have encountered crashes with certain versions of numpy, and ended up with numerous hours of debugging to no avail.
This was the main reason to pin numpy.

I'm open to any suggestions that can work around this problem (of having to freeze numpy so that the dynamical core does not crash without warning).

**Comment by JoyMonteiro** [comment]
The latest version of climt (just released) removes this restriction. However, please install climt inside a virtual environment since we are likely to pin numpy versions for stability.
