### ISSUE TITLE
Publication with the Journal of Open Research Software?

### ISSUE THREAD

**Issue by DamienIrving** [CliMT/climt#13]
This issue overlaps with [one I just posted at the sympl repo](https://github.com/mcgibbon/sympl/issues/6), but I was wondering if you'd considered publishing the details of climt with the [Journal of Open Research Software](https://openresearchsoftware.metajnl.com/)? It's a great way to get academic credit for all the hard work involved in releasing and maintaining research software. I'm an Associate Editor with JORS and would love to see a submission on climt.

**Comment by JoyMonteiro** [comment]
Hello Damien,

Thanks for the invitation! We are considering submitting a paper to GMD, but I can see that the scope of articles in JORS is quite different. GMD will have more readers from our own field, and I would like your
opinion about this issue.

There are some parts of the core API that I am going to write in the coming months, and I intend to start writing a paper once I'm done with that so that all that we have to offer will be documented.

**Comment by DamienIrving** [comment]
I think GMD probably is more appropriate, given the readership. Good luck with the submission.

**Comment by JoyMonteiro** [comment]
Thanks!
