### ISSUE TITLE
Failed building wheel for climt

### ISSUE THREAD

**Issue by TanguiP** [CliMT/climt#164]
* CliMT version: 0.17.5
* Python version:
* Operating System: Microsoft Windows 11 Professionnel - 10.0.22621 N/A build 22621

### Description

Hi,
When installing climt with pip (or pip3), I get the issue "Failed building wheel for climt" (see text file pip.txt)
_pip install climt_
I get the issue "Failed building wheel for climt" (see text file pip.txt)
I got similar issues for previous versions of CliMT from 9 and 15 at least. 

I tried to also install it by directly downlowing the librairy and then using:
_pip install -r requirements_dev.txt
python setup.py install_
The first one worked but not the second one. 

[pip_issue.txt](https://github.com/CliMT/climt/files/13058507/pip_issue.txt)
the second one.

**Comment by HarrisPyper** [comment]
I got the same error, I have created a vitural env and degrade to python 3.8.11, but wheel still doesn't work. I install on Anaconda on windows.

**Comment by TanguiP** [comment]
Hi @HarrisPyper, still not working for me. I wasn't able to find a robust fix to the installation problem so I resigned myself to using a packadge for my class...

**Comment by JoyMonteiro** [comment]
Sorry for the delay in replying. Since Windows now has robust support for unix environments via [WSL](https://learn.microsoft.com/en-us/windows/wsl/install), we no longer plan to support windows builds in the near term due to lack of time. We recommend installing Ubuntu Linux via WSL, and install climt there.

**Comment by HarrisPyper** [comment]
> Sorry for the delay in replying. Since Windows now has robust support for unix environments via [WSL](https://learn.microsoft.com/en-us/windows/wsl/install), we no longer plan to support windows builds in the near term due to lack of time. We recommend installing Ubuntu Linux via WSL, and install climt there.

Hi, thanks for your reply. I degraded python to 3.6 and installed climt 16.3, but when I ran the example cases, I got warnings and errors, I reckon it's because of the lower versions of some python libraries.

Condensation/evaporation/radiation/wind/turbulence are the main process in my case, can I use climt 16.3 to build our own fog model? (Not too familiar with sympl & climt at the moment, just installed climt 16.3 & sympl.)

**Comment by HarrisPyper** [comment]
> Hi @HarrisPyper, still not working for me. I wasn't able to find a robust fix to the installation problem so I resigned myself to using a packadge for my class...

I degraded python to 3.6 and installed climt 16.3, but got warnings and errors when runnng example cases, not too sure if it's due to lower version of python.

**Comment by HarrisPyper** [comment]
> Sorry for the delay in replying. Since Windows now has robust support for unix environments via [WSL](https://learn.microsoft.com/en-us/windows/wsl/install), we no longer plan to support windows builds in the near term due to lack of time. We recommend installing Ubuntu Linux via WSL, and install climt there.

Thanks for reply, I installed on linux and run cases now.

**Comment by JoyMonteiro** [comment]
Great! Closing this issue for now
