### ISSUE TITLE
Incompatibility with Sympl v0.3.1

### ISSUE THREAD

**Issue by lkluft** [CliMT/climt#27]
* CliMT version: Latest `develop` branch
* Python version: 3.6.3
* Operating System: Linux

### Description

After updating to Sympl v0.3.1 it is no longer possible to import CliMT.

The problem is (amongst others) located at line:

https://github.com/CliMT/climt/blob/c3862568a6c457ec3cc65870fef679faee7057b6/climt/_core/constants.py#L91-L92

I don't know if this is fixed in #18 to be honest I lost track of that PR 😉 

### What I Did

```python
import climt
```

### Outcome
```
AttributeError                            Traceback (most recent call last)                                                      
<ipython-input-3-e4ba426e2011> in <module>()                    
----> 1 import climt            

/mnt/lustre02/work/um0878/users/lkluft/dev/climt/climt/__init__.py in <module>()                                                 
      4 from sympl import set_constant                          
      5                         
----> 6 from ._core import (    
      7     get_default_state, mass_to_volume_mixing_ratio,     
      8     get_interface_values, constant_library,             

/mnt/lustre02/work/um0878/users/lkluft/dev/climt/climt/_core/__init__.py in <module>()                                           
      8     ClimtSpectralDynamicalCore                          
      9 )                       
---> 10 from .constants import (constant_library, get_constant, 
     11                         reset_constant_library, list_available_constants,                                                
     12                         add_constants_from_dict, set_constants_from_dict)                                                

/mnt/lustre02/work/um0878/users/lkluft/dev/climt/climt/_core/constants.py in <module>()                                          
    116                         
    117                         
--> 118 constant_library = ConstantLibrary()                    
    119                         
    120                         

/mnt/lustre02/work/um0878/users/lkluft/dev/climt/climt/_core/constants.py in __init__(self)                                      
     82     def __init__(self): 
     83                         
---> 84         self.__init_constant_library()                  
     85                         
     86     def __init_constant_library(self):                  

/mnt/lustre02/work/um0878/users/lkluft/dev/climt/climt/_core/constants.py in __init_constant_library(self)                       
     89         """             
     90                         
---> 91         self._original_constants = deepcopy(sympl.default_constants)                                                     
     92         self.current_constants = sympl.default_constants
     93                         

AttributeError: module 'sympl' has no attribute 'default_constants'      
```

Cheers,
Lukas

**Comment by mcgibbon** [comment]
Thanks for noticing! This was expected. It isn't supposed to be fixed in that PR, but will be done in the next one. There were some important breaking changes introduced to Sympl so we can make CliMT's code... simpler.

Until this is resolved it's worth keeping this issue open. For now revert to Sympl 0.2.1. When CliMT gets upgraded your code will break again until you upgrade Sympl.

**Comment by mcgibbon** [comment]
Correction, this actually might be fixed in that PR. I also lost track of it.

**Comment by JoyMonteiro** [comment]
@lkluft I will ensure that a released version of climt will work with a released version of sympl. For development versions, I recommend using my fork of sympl. All my own development happens assuming the sympl being used is the one on my fork. I normally fix things that arise due to any changes that might have happened in sympl, but my turnover time on that front is normally much slower.

In fact, if you see requirements_dev.txt, it points to my fork.

**Comment by mcgibbon** [comment]
I didn't know about your fork, @JoyMonteiro - thanks for pointing that out!

The best practice is to use [semantic versioning](https://semver.org/), not have so many breaking changes. and limit backwards-incompatible API changes to full version increases while giving deprecation warnings and whatnot in minor versions. Then you know if code breaks it's "oh because Sympl 3 is different from Sympl 2", similar to the kind of Python 3/2 errors you get. But while we're in pre-1.0 territory, we'll continue to do things this way.

Oh, actually I guess what I just said is [also accepted](https://semver.org/#spec-item-4) under semantic versioning.

**Comment by JoyMonteiro** [comment]
Fixed in the new release!

**Comment by mcgibbon** [comment]
Note: fixed by #28

**Comment by lkluft** [comment]
Thank you very much! Works like a charm 😉 

PS.: The binary wheels are super nice! :+1:

**Comment by JoyMonteiro** [comment]
Great! A relief to know the wheels actually work :)
