### ISSUE TITLE
RRTMG stores constants at initialization

### ISSUE THREAD

**Issue by mcgibbon** [CliMT/climt#42]
Currently RRMTG uses constants that are set at initialization, and will not have its results reflect updates to constants (by `set_constant`) that occur between calls. In other components I just had the constant setting code get called at the start of every call, but it's not obvious to me that calling `initialise_rrtm_radiation` at the start of every function call is safe. Is it safe?

**Comment by JoyMonteiro** [comment]
There is nothing in the code that makes it unsafe, but I'm worried that it might incur additional compute costs since it reads huge arrays to initialise things.

It gets worse for GFS, which has a huge setup time, and any call to `set_constant` will require GFS to be reset.

For now, I think we should stick to a basic use-case where `set_constant` is only called at the top of the script, or at the top of a loop which would involve setting constants, creating components and running the model. While the alternative is very attractive, I don't think we can do this in any straightforward way, especially when dycores come into the picture.

**Comment by mcgibbon** [comment]
It should be relatively straightforward to write new Fortran routines that
update the Fortran constants. If those constants aren't involved in cached
arrays made on initialization then I think this is the best route.

**Comment by JoyMonteiro** [comment]
Fixed in latest release.
